# -*- mode: python ; coding: utf-8 -*-

datas = [
    ('frontend', 'frontend'),
    ('backend/skills', 'backend/skills'),
    ('backend/workflows', 'backend/workflows'),
]

hiddenimports = [
    'backend.main',
    'backend.routers.chat',
    'backend.routers.constitution',
    'backend.routers.experts',
    'backend.routers.files',
    'backend.routers.grind',
    'backend.routers.i18n',
    'backend.routers.knowledge',
    'backend.routers.lan',
    'backend.routers.projects',
    'backend.routers.proxy',
    'backend.routers.settings',
    'backend.routers.skills',
    'backend.routers.update',
    'backend.routers.vault',
    'backend.routers.workflows',
    'backend.skills.css_color',
    'backend.skills.doc_write',
    'backend.skills.file_create',
    'backend.skills.file_edit',
    'backend.skills.file_peek',
    'backend.skills.file_tree',
    'backend.skills.html_render',
    'backend.skills.json_tool',
    'backend.skills.ppt_create',
    'backend.skills.regex_test',
    'backend.skills.repo_stats',
    'backend.skills.text_summarize',
    'backend.skills.todo_scan',
    'backend.skills.terminal',
    'backend.skills.web_fetch',
    'backend.skills.web_search',
    'backend.skills.word_create',
    'backend.skills.chart_create',
    'backend.skills.qrcode_create',
    'backend.skills.python_api_extract',
    'backend.skills.html_bundle',
    'backend.skills.browser_automation',
    'backend.skills.computer_use',
    'backend.skills.screenshot_to_code',
    # 多模态文件解析依赖（files.py 内函数级延迟导入，需显式声明）
    'openpyxl',
    'pdfplumber',
    'qrcode',
    'qrcode.image.svg',
    'pptx',
    'pptx.oxml',
    'docx',
    'docx.oxml',
    'webview.platforms.edgechromium',
    'uvicorn.lifespan.on',
    'uvicorn.protocols.http.auto',
    'uvicorn.protocols.websockets.auto',
    'uvicorn.loops.auto',
]

excludes = [
    'kivy',
    'gi',
    'gtk',
    'tkinter',
    # ML/AI 大包（项目未使用，Blake2B 哈希向量无需神经网络嵌入）
    'torch',
    'torchvision',
    'torchaudio',
    'transformers',
    'sentence_transformers',
    'sentencepiece',
    'triton',
    'paddleocr',
    'paddlex',
    'paddle',
    'chromadb',
    'onnxruntime',
    'safetensors',
    'tokenizers',
    'sklearn',
    'scikit-learn',
    # 数据科学大包（项目未使用）
    'numpy',
    'scipy',
    'pandas',
    'matplotlib',
    # 3D/CAD/视觉（项目未使用）
    'vtk',
    'trame',
    'cadquery',
    'trimesh',
    'cv2',
    'opencv-python',
    'opencv-contrib-python',
    'casadi',
    'sympy',
    # GUI 框架（项目使用 pywebview，不需要 Qt/Tk）
    'PyQt5',
    'PyQt6',
    'PySide2',
    'PySide6',
    'customtkinter',
]

a = Analysis(
    ['desktop.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='SLATE',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['app.ico'],
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='SLATE',
)
